name: 🔥 Auto Test with GitHub Actions

on: [push, pull_request]  # Chạy khi có push hoặc pull request

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Chạy trên hệ điều hành Linux

    steps:
      - name: 📥 Checkout source code
        uses: actions/checkout@v3

      - name: 🔧 Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'  # Chọn phiên bản .NET bạn đang dùng

      - name: 📦 Restore dependencies
        run: dotnet restore

      - name: 🔨 Build project
        run: dotnet build --no-restore --configuration Release

      - name: 📂 Ensure test data exists
        run: |
          mkdir -p demo5/bin/Debug/data
          cp demo5/data/test.csv demo5/bin/Debug/data/test.csv

      - name: 🧪 Run unit tests
        run: dotnet test --no-build --verbosity normal
